# Generated by Django 3.2 on 2021-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210420_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dueTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
